SELECT * FROM employees;

SELECT COUNT(EMPLOYEE_ID) AS Num
FROM employees;

SELECT * FROM DEPARTMENTS d;

SELECT employee_id, first_name, last_name
FROM EMPLOYEES e;

SELECT first_name, phone_number, hire_date, salary
FROM EMPLOYEES e;

SELECT
	e.FIRST_NAME AS 성,
	e.LAST_NAME AS 이름,
	e.SALARY AS 급여,
	e.PHONE_NUMBER AS 전화번호,
	e.EMAIL AS 이메일,
	e.HIRE_DATE AS 입사일
FROM EMPLOYEES e;

SELECT 
	e.EMPLOYEE_ID AS "empNO",
	e.FIRST_NAME AS "E-mail",
	e.SALARY AS "연 봉"
FROM EMPLOYEES e;

SELECT
	e.LAST_NAME AS 이름,
	e.PHONE_NUMBER AS 전화번호,
	e.HIRE_DATE AS 입사일,
	e.SALARY AS 급여
FROM EMPLOYEES e;

SELECT
	e.EMPLOYEE_ID AS 사원번호,
	e.LAST_NAME AS 이름,
	e.FIRST_NAME AS 성,
	e.SALARY AS 급여,
	e.PHONE_NUMBER AS 전화번호,
	e.EMAIL AS 이메일,
	e.HIRE_DATE AS 입사일
FROM EMPLOYEES e;

SELECT first_name || ' ' || last_name
FROM EMPLOYEES e;

SELECT CONCAT(CONCAT(first_name, ' '), last_name) AS 이름
FROM EMPLOYEES e;

SELECT
	e.FIRST_NAME,
	e.SALARY AS 월급,
	e.SALARY*12 AS 연봉,
	(e.SALARY+300)*12 AS 내년연봉
FROM EMPLOYEES e;

SELECT e.JOB_ID
FROM EMPLOYEES e;

SELECT 
	e.FIRST_NAME || '-' || e.LAST_NAME AS 성명,
	e.SALARY AS 급여,
	e.SALARY*12 AS 연봉,
	(e.SALARY*12)+5000 AS 연봉2,
	e.PHONE_NUMBER AS 전화번호
FROM EMPLOYEES e;


SELECT e.FIRST_NAME
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID < 40;

SELECT
	e.FIRST_NAME || ' ' || e.LAST_NAME AS 이름,
	e.SALARY * 12 AS 연봉
FROM EMPLOYEES e
WHERE e.SALARY >= 15000;

SELECT
	e.FIRST_NAME AS 이름,
	e.HIRE_DATE AS 입사일
FROM EMPLOYEES e 
WHERE e.HIRE_DATE > '2007/01/01'

SELECT e.SALARY AS 연봉
FROM EMPLOYEES e 
WHERE e.FIRST_NAME = 'Lex'

SELECT e.FIRST_NAME , e.SALARY 
FROM EMPLOYEES e 
WHERE e.SALARY >= 14000 AND e.SALARY <= 17000;

SELECT
	e.FIRST_NAME AS 이름,
	e.HIRE_DATE AS 입사일
FROM EMPLOYEES e 
WHERE e.HIRE_DATE >= '2004/01/01'
AND e.HIRE_DATE <= '2005/12/31';

SELECT
	e.FIRST_NAME AS 이름,
	e.HIRE_DATE AS 입사일
FROM EMPLOYEES e 
WHERE e.HIRE_DATE >= TO_DATE(20040101, 'YYYY/MM/DD')
AND e.HIRE_DATE <= TO_DATE(20051231, 'YYYY/MM/DD');

SELECT
	e.FIRST_NAME AS 이름,
	e.SALARY AS 급여
FROM EMPLOYEES e 
WHERE e.SALARY IN (2100, 3100, 4100, 5100);

SELECT e.FIRST_NAME AS 성, e.LAST_NAME AS 이름, e.SALARY AS 급여
FROM EMPLOYEES e 
WHERE e.FIRST_NAME LIKE 'L%';

SELECT e.FIRST_NAME AS 이름, e.SALARY AS 급여
FROM EMPLOYEES e 
WHERE e.FIRST_NAME LIKE '%am%';

SELECT e.FIRST_NAME , e.SALARY , e.COMMISSION_PCT 
FROM EMPLOYEES e 
WHERE e.COMMISSION_PCT IS NULL;

SELECT e.FIRST_NAME AS 이름, e.SALARY AS 급여, e.COMMISSION_PCT AS "커미션 비율"
FROM EMPLOYEES e 
WHERE e.COMMISSION_PCT IS NOT NULL;

SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS 이름
FROM EMPLOYEES e 
WHERE e.COMMISSION_PCT IS NULL
AND e.MANAGER_ID IS NULL;

SELECT *
FROM EMPLOYEES e 
WHERE e.MANAGER_ID = '100';

SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS 이름, salary
FROM EMPLOYEES e 
ORDER BY e.SALARY ASC;

SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS 이름, salary
FROM EMPLOYEES e 
WHERE e.SALARY >= 9000
ORDER BY e.SALARY DESC, 1;

SELECT 
	e.DEPARTMENT_ID AS 부서번호,
	e.SALARY AS 이름,
	e.FIRST_NAME || ' ' || e.LAST_NAME AS 이름
FROM EMPLOYEES e 
ORDER BY e.DEPARTMENT_ID ;

SELECT 
	e.DEPARTMENT_ID AS 부서번호,
	e.SALARY AS 이름,
	e.FIRST_NAME || ' ' || e.LAST_NAME AS 이름
FROM EMPLOYEES e 
ORDER BY 1 ASC, 2 DESC;

SELECT
	e.FIRST_NAME ,
	LPAD(e.FIRST_NAME , 10, '*'),
	RPAD(e.FIRST_NAME , 10, '*')
FROM EMPLOYEES e 

SELECT 
	e.FIRST_NAME || ' ' || e.LAST_NAME AS 이름,
	e.HIRE_DATE ,
	MONTHS_BETWEEN(sysdate, e.HIRE_DATE ) AS 근속월,
	MONTHS_BETWEEN(sysdate, e.HIRE_DATE ) / 12 AS 근속년
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID = 110;

SELECT
	e.FIRST_NAME || ' ' || e.LAST_NAME AS 이름,
	TO_CHAR(e.SALARY * 12, '$999,999.99') "SAL"
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID = 110;

SELECT
	sysdate,
	TO_CHAR(sysdate, 'YYYY"년 "MM"월 "DD"일 "HH24"시 "MI"분 "SS"초"') AS "현재 시간"
FROM dual;



